services:
  web:
    build:
      context: .
      target: production
    container_name: keywrods-embedding-fastapi
    volumes:
      - .:/code
    ports:
      - "8000:80"
    env_file:
      - .env.local
    command: fastapi dev src/main.py --host 0.0.0.0 --port 80

volumes:
  fastapi_dev:
